	processor 16f877
	include<p16f877.inc>
	
	ORG 0
	GOTO inicio
	ORG 5
inicio: BSF STATUS,RP0		;PONEMOS RP1 EN 1 DEL REG STATUS
	BCF STATUS,RP1			;PONEMOS RP0 EN 0 DEL REG STATUS, UBICANDONOS EN EL BANCO 01
	BSF TXSTA,BRGH			;PRENDEMOS EL BIT BRGH DEL REG TXSTA SEÑALANDO QUE ES TRANSMISION DE ALTA VELOCIDAD
	MOVLW D'129'			;CARGAMOS EL VALOR DECIMAL AL REG W
	MOVWF SPBRG				;MANDAMOS EL VALOR DE W AL SPBRG QUE DA EL VALOR DEL BAUD-RATE=9600
	BCF TXSTA,SYNC			;PONEMOS EN 0 EL BIT SYNC, PARA COMUNICACION ASINCRONA
	BSF TXSTA,TXEN			;ACTIVAMOS LA TRANSMISION DE DATOS

	BCF STATUS,RP0			;REGRESAMOS AL BANCO 00
	BSF RCSTA,SPEN			;HABILITAMOS EL PUERTO SERIE
	BSF RCSTA,CREN			;COMUNICACION CONTINUA (ASYNC)
recibe: BTFSS PIR1,RCIF		;CHECAMOS EL BIT RCIF DE PIR1, PARA VER SI SE COMPLETO LA RECEPCION DEL MENSAJE
	GOTO recibe				;SINO SE REGRESA EN LOOP
	MOVF RCREG,W			;SI SE COMPLETO EL MENSAJE, MANDAMOS ESTE AL REG W
	MOVWF TXREG				;MANDAMOS LO QUE CONTENGA W AL REG TXREG QUE CONTENDRA EL MENSAJE A MANDAR
	BSF STATUS,RP0			;NOS MOVEMOS AL BANCO 01
transmite: BTFSS TXSTA,TRMT	;CHECAMOS EL ESTADO DE LA TRANSMISION
	GOTO transmite			;SINO SE HA TERMINADO DE TRANSMITIR REGRESAMOS EN LOOP
	BCF STATUS,RP0			;SI SE TERMINO DE TRANSMITIR REGRESAMOS AL BANCO 00
	GOTO recibe				;REGRESAMOS AL COMPORTAMIENTO DE RECEPCION
	
;FUNCIONALMENTE, RECIBE UN MENSAJE Y REGRESA EL MISMO MENSAJE AL TRANSMISOR
	END